### ISSUE TITLE
Panic: dial tcp

### ISSUE THREAD

**Issue by raj23689** [aditya-K2/gomp#23]
error:
```sh 
Could Not Connect to MPD Server
Make Sure You Mention the Correct MPD Port in the config file.
panic: dial tcp [::1]:6600: connect: connection refused

goroutine 1 [running]:
main.main()
	github.com/aditya-K2/gomp/main.go:29 +0x21cf
```

My ```config.yml```

```yml
MUSIC_DIRECTORY: "~/Music/"
ADDITIONAL_PADDING_X : 9
ADDITIONAL_PADDING_Y : 17
IMAGE_WIDTH_EXTRA_X  : -1.1
IMAGE_WIDTH_EXTRA_Y  : -3.75
MPD_PORT : "6600"
togglePlayBack : [ "p", "SPACE", "]" ]
CACHE_DIR : "~/.config/gomp/cache/"
```

My ```mpd.conf```

```conf
music_directory "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file "~/.config/mpd/mpd.db"
log_file "~/.config/mpd/mpd.log"
pid_file "~/.config/mpd/mpd.pid"
state_file "~/.config/mpd/mpdstate"

audio_output {
        type "pulse"
        name "pulse audio"
}

audio_output {
	type                    "fifo"
	name                    "my_fifo"
	path                    "/tmp/mpd.fifo"
	format                  "44100:16:2"
}

bind_to_address "127.0.0.1"
port "6600"
```
