### ISSUE TITLE
album art doesnt show up on any songs even though audio file has an embeded album art

### ISSUE THREAD

**Issue by Felix-Kyun** [aditya-K2/gomp#38]
![10-49-44-PM_2022-10-22](https://user-images.githubusercontent.com/99094581/197353796-0394e4de-493c-4b0c-9229-34786b961df7.png)

i've used `ffmpeg` to extract the image from audio file, 
my config 
```yaml
MPD_PORT : "6600"
MUSIC_DIRECTORY : "~/Media/music/"
SEEK_OFFSET : 5
CACHE_DIR : "~/.config/gomp/.cache/"
DEFAULT_IMAGE_PATH : "~/.config/gomp/default_art.png"
```
and the audio i was playing was located in `~/Media/music/nightcore/`
