### ISSUE TITLE
`No Image Extracted`, reverts to fallback image.

### ISSUE THREAD

**Issue by beune** [aditya-K2/gomp#55]
Version: 1.0.1.
Terminal: alacritty 0.12

When I open up `gomp` I get the error: `No Image Extracted`, and it shows the fallback image.

![2023-05-11_14-41](https://github.com/aditya-K2/gomp/assets/47817451/403fc2b5-240c-439e-886c-cad9158e300f)

How can this be fixed? I read in earlier issues that only certain filetypes are supported. I only have `mp3`s in my library.

**Comment by aditya-K2** [comment]
> I read in earlier issues that only certain file types are supported. I only have `mp3`s in my library.

This used to be the case earlier but now most of the file formats are supported  `(FLAC, m4a, OGG, MP3)`. The fallback image is rendered when the given file doesn't contain any embedded image. If you want `gomp` to download the cover art from LastFM for you, you can enable it by providing the following information in the `~/.config/gomp/config.yml`

```yml
GET_COVER_ART_FROM_LAST_FM : True 
LASTFM_API_KEY: "YOUR API KEY HERE"
LASTFM_API_SECRET: "YOUR API SECRET HERE"
```
You can read more about it in the [documentation](https://aditya-k2.github.io/gomp/)
